CREATE DATABASE scheduling;
CREATE DATABASE auth;
CREATE DATABASE rating;
GRANT ALL PRIVILEGES ON DATABASE "scheduling" TO "appUser";
GRANT ALL PRIVILEGES ON DATABASE "auth" TO "appUser";
GRANT ALL PRIVILEGES ON DATABASE "rating" TO "appUser";

