server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    consul:
      discovery:
        register: false
        register-health-check: false
