create table if not exists users
(
    id            int8 generated by default as identity,
    active        boolean      not null,
    created_date  timestamp    not null,
    email         varchar(255),
    modified_date timestamp    not null,
    password      varchar(128) not null,
    role          varchar(32)  not null,
    username      varchar(32)  not null,
    primary key (id)
);
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
