create table ratings
(
    id                      int8 generated by default as identity,
    doctor_id               int8 not null,
    rating                  numeric(19, 2),
    total_number_of_ratings int4,
    primary key (id)
);
create table surveys
(
    id             int8 generated by default as identity,
    appointment_id int8      not null,
    doctor_id      int8      not null,
    end_time       timestamp not null,
    user_id        int8      not null,
    processed      boolean   not null,
    rating         int4,
    start_time     timestamp not null,
    primary key (id)
);
alter table if exists ratings
    add constraint UK_c7nj5p3yh5mrk937lw7hli93b unique (doctor_id);
alter table if exists surveys
    add constraint UK_sa1pk4r382ng9qtwetddrog49 unique (appointment_id);
