create table appointments
(
    id            int8 generated by default as identity,
    created_date  timestamp not null,
    modified_date timestamp not null,
    patient       int8      not null,
    timeslot_id   int8,
    primary key (id)
);
create table doctor_specialty
(
    doctor_id    int8 not null,
    specialty_id int8 not null,
    primary key (doctor_id, specialty_id)
);
create table doctors
(
    id            int8 generated by default as identity,
    created_date  timestamp not null,
    modified_date timestamp not null,
    rating        numeric(19, 2),
    user_id       int8      not null,
    primary key (id)
);
create table specialties
(
    id            int8 generated by default as identity,
    created_date  timestamp    not null,
    description   varchar(255),
    modified_date timestamp    not null,
    name          varchar(255) not null,
    primary key (id)
);
create table timeslots
(
    id         int8 generated by default as identity,
    end_time   timestamp not null,
    free       boolean   not null,
    start_time timestamp not null,
    doctor_id  int8,
    primary key (id)
);
alter table if exists doctors
    add constraint UK_t1f6cueqyjwx5ghew9ar1exe3 unique (user_id);
alter table if exists specialties
    add constraint UK_bhb8s9o5hv30lkbidtod9cixc unique (name);
alter table if exists appointments
    add constraint FK9jpx797ytvnqjpd9v3i4e9n8l foreign key (timeslot_id) references timeslots;
alter table if exists doctor_specialty
    add constraint FK4917gxpqbpgy2bl7167thi4xx foreign key (specialty_id) references specialties;
alter table if exists doctor_specialty
    add constraint FK2hk0t6mjxwnv8y85yd6sj5ktp foreign key (doctor_id) references doctors;
alter table if exists timeslots
    add constraint FK7n2y5a0e7t9us9nkaih4ew94 foreign key (doctor_id) references doctors;
